import type { Metadata } from "next";
import "./globals.css";
import { AuthProviderServer } from "@/lib/providers/AuthProvider.server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={" w-full h-full bg-[rgb(17_24_39)]"}>
        <AuthProviderServer>{children}</AuthProviderServer>
      </body>
    </html>
  );
}
